# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Vz0n's blog"
lang: "es-ES"
email: me@vzondev.cf
description: >-
  El blog de Vz0n. Por aquí encontrarás writeups de máquinas de HackTheBox u otras
  plataformas y posts de guías, historias/anécdotas de mi vida, experimentos... etc
baseurl: ""
url: "https://blog.vzondev.cf"
permalink: /:categories/:title
twitter_username: iVz0n
github_username:  Vz0n
author: Vz0n

# Build settings
theme: jekyll-theme-cayman
pagination: 
  enabled: true
webrick:
  headers:
    X-Site: 'Blog'
plugins: 
- jekyll-seo-tag
- jekyll-paginate-v2

defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: post

exclude:
- README.md
- Gemfile
- node_modules/
- vendor/
- .gitattributes
- .gitignore


