# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: "Vz0n's blog"
lang: "es-ES"
email: me@vzondev.cf
description: >-
  El blog de Vz0n. Por aquí encontrarás writeups de máquinas de HackTheBox u otras
  plataformas y posts de guías, historias/anécdotas de mi vida, experimentos... etc
baseurl: ""
url: "https://blog.vzondev.cf"
canonical_url: "https://blog.vzondev.cf"
twitter_username: iVz0n
github_username:  Vz0n
author: Vz0n

# Build settings
theme: jekyll-theme-cayman
webrick:
  headers:
    X-Site: 'Blog'
plugins: 
#- jekyll-remote-theme
- jekyll-seo-tag

#remote_theme: "https://github.com/pages-themes/cayman"
# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
- README.md
- Gemfile
- node_modules/
- vendor/
- .gitattributes
- .gitignore
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

